### ISSUE TITLE
Crear función SetTimeout

### ISSUE THREAD

**Issue by maximocanedo** [maximocanedo/PROGIII-TPI#14]
La tarea consiste en crear una función que reciba dos parámetros: un int que serían los segundos / milisegundos, y una función, como objeto de tipo Action, que se ejecutará pasados los segundos.
La definición podría ser así:
`public void SetTimeout(Action funcionAEjecutar, int segundos) { /* ... */ }`
Y se debería poder usar así:
`SetTimeout(() => {
   Utils.MostrarMensaje("Han pasado 5 segundos!", this.Page, GetType());
}, 5);`

**Comment by Oli-Hanczyc** [comment]
Bueno, agregué la función propuesta en la clase estática Utils, solo que en vez de poner los segundos como una variable int, la establecí como double para que coincidiera con la del parámetro de la función EsperarSegundos (que también es double), y poder reutilizarla. Supongo que la función enviada por parámetro se ejecuta con Invoke()...
Así quedó el código:
```
public static void SetTimeout(Action funcionAEjecutar, double segundos) {
    EsperarSegundos(segundos);
    funcionAEjecutar.Invoke();
}
```
Y también muestro la de EsperarSegundos:
```
public static void EsperarSegundos(double cantSeg)
{
    // Creo la cadena para convertir en TimeSpan:
    string s = "0.00:00:" + cantSeg.ToString().Replace(",", ".");
    TimeSpan ts = TimeSpan.Parse(s);

    // Le añado la diferencia a la hora actual:
    DateTime t1 = DateTime.Now.Add(ts);

    // Guardo la fecha y hora actual en una variable DateTime:
    DateTime t2 = DateTime.Now;

    // Mientras no haya pasado el tiempo indicado:
    while (t2 < t1)
    {
        // Asignar la hora actual:
        t2 = DateTime.Now;
    }
}
```
Los cambios los subí al repositorio. Igualmente si consideran hacer una función para utilizar segundos enteros (o sea, de tipo int), o utilizar float en vez de double (por el tema de que ocupa menos espacio que double, aunque tampoco es tanto), podemos agregar o cambiar eso.
Saludos.

**Comment by maximocanedo** [comment]
Buenas. Desconozco si los Actions se pueden ejecutar con .Invoke(). Yo usualmente los ejecuto como funciones normales.

`funcionAEjecutar()`

Pero si funciona con Invoke está bien.
