### ISSUE TITLE
Adaptar nombres de WebForms

### ISSUE THREAD

**Issue by maximocanedo** [maximocanedo/PROGIII-TPI#15]
La tarea consiste en readaptar el código (El diseño no importa), de las páginas para que el sistema de nombres sea más organizado.
Por ejemplo, que todas las páginas que tengan que ver con agregar un registro X, se llamen "Agregar.aspx".

Se trata de las siguientes páginas

- [x] Tipos/IgresarTipodePrductos.aspx (Cambiar a Tipos/Agregar.aspx)
- [x] Tipos/VerTipoDeProducto.aspx (Cambiar a Tipos/Administrar.aspx, dado que provee una tabla de productos)
- [x] Animales/AgregarAnimal.aspx (Cambiar a Animales/Agregar.aspx)
- [x] Animales/VerAnimales.aspx (Cambiar a Animales/Administrar.aspx)

**Comment by maximocanedo** [comment]
Advierto que no es sólo cambiar los nombres de los archivos, sino también las referencias y los nombres de las clases que tienen los WebForms en cuestión.

**Comment by Mizzar229** [comment]
En espera a que terminen con la carpeta de Productos para finalizarlo.

**Comment by maximocanedo** [comment]
En vista de que esta Issue no se completó, lleva más de cinco días asignada y que es necesario para poder continuar con el trabajo, me autoasigné esta Issue y por ahora está hecha la página de Categorías > Administrar, como está en el commit 3fd68a8 .
