### ISSUE TITLE
Verificar que no exista un registro en la base de datos al agregar un registro Animal

### ISSUE THREAD

**Issue by maximocanedo** [maximocanedo/PROGIII-TPI#2]
Actualmente, si se ingresa a la página en Vistas/Animales/Agregar.aspx con las credenciales adecuadas, e ingresa un código de un registro que ya existía, no le presenta ningún tipo de restricción o límite.
Debería impedir la creación del registro si el código ya existe en la base.

**Comment by Jean5011** [comment]
Me encargo es esta
