### ISSUE TITLE
Crear WebForm de Editar Proveedores

### ISSUE THREAD

**Issue by maximocanedo** [maximocanedo/PROGIII-TPI#24]
La tarea consiste en crear un WebForm aparte para editar Proveedores.

**Comment by Mizzar229** [comment]
Casi terminado, solo falta que el botón de editar tenga su funcionalidad y se relacione con el Command

**Comment by maximocanedo** [comment]
Ahora me encargo de eso

**Comment by maximocanedo** [comment]
Lo de Proveedores ya lo había terminado hoy con el commit 65b0800.

**Comment by maximocanedo** [comment]
Considero que Editar Proveedores ya está funcionando, salvo algunas cosas que están detalladas en posteriores Issues y que no tienen que ver con esta en específico.
