### ISSUE TITLE
Avisar sobre resultado de Agregar Categoría

### ISSUE THREAD

**Issue by maximocanedo** [maximocanedo/PROGIII-TPI#37]
La tarea consiste en avisar al usuario si la Categoría se pudo agregar o no, como también de posibles errores que hayan ocurrido en el proceso, preferentemente mediante el uso de `Utils.ShowSnackbar()`.

**Comment by maximocanedo** [comment]
¿Cómo vamos @Jean5011 con esto?
Recomiendo que al hacer commits que resuelvan o que trabajen en esta Issue agregues el número de Issue:
`#37 ... [ Resto del mensaje de commit ]` <- Para que aparezca en esta pantalla.
`Fixes #37 ... [Resto del mensaje del commit]` <- Para de paso cerrarlo.
Si ya está hecho recomiendo que cierres esta Issue.
Saludos.

**Comment by Jean5011** [comment]
ya lo termine
