### ISSUE TITLE
Agregar mensaje de Confirmacion

### ISSUE THREAD

**Issue by Mizzar229** [maximocanedo/PROGIII-TPI#42]
Al agregar un producto o editar un producto, antes de que dicho registro se guarde, es necesario que aparezca un mensaje de confirmación preguntando al usuario si esta seguro de que desea continuar y guardar el registro.

**Comment by maximocanedo** [comment]
Ideas posibles:

- Crear un método en Utils que permita abrir, y administrar objetos MaterialDialog para crear Diálogos de confirmación.
- Crear WebForms que sirvan a modo de confirmación.
- (No recomendado) Usar la función nativa de Javascript, "prompt".

**Comment by maximocanedo** [comment]
Comienzo con Animales.

**Comment by maximocanedo** [comment]
Continuo con Empleados

**Comment by maximocanedo** [comment]
Productos está ocupado. Continuo con Proveedores.

**Comment by maximocanedo** [comment]
Proveedores ya está. Continúo con Tipos de Producto.

**Comment by maximocanedo** [comment]
Me faltaba todavía.

**Comment by maximocanedo** [comment]
- [ ] Ventas
- [ ] Tipos
- [ ] Proveedores
- [ ] Productos
- [ ] Empleados
- [ ] Animales
- [ ] Sesiones
