### ISSUE TITLE
Iniciar Sesion presionando Enter

### ISSUE THREAD

**Issue by Mizzar229** [maximocanedo/PROGIII-TPI#46]
Estaría bueno que se pudiera iniciar sesión presionando la tecla Enter para mas comodidad, pero no es obligatorio

**Comment by maximocanedo** [comment]
Cierro esta Issue porque, después de investigar un poco llegué a la conclusión de que es muy complicado realizar esto.
Se necesita manipular el evento mediante Javascript y luego hacer un PostBack.
![image](https://github.com/maximocanedo/PROGIII-TPI/assets/103539894/135b4899-67e5-4e1a-9c17-bcf96c0d33fd)
![image](https://github.com/maximocanedo/PROGIII-TPI/assets/103539894/a20d426d-cd6f-441b-b659-97747f9574a7)
![image](https://github.com/maximocanedo/PROGIII-TPI/assets/103539894/6d77f698-7281-494a-9ce4-17b4c58697ba)

El problema con esto es que necesita hacer PostBack para que C# lo pueda manejar. 
Y con PostBack, imposibilita el ingreso de la contraseña, dado que cuando se hace click en el `txtClave`, se realiza PostBack, y si se desactiva el PostBack no funciona nada.

Doy por cerrado esta Issue. Aunque si se encuentra una solución más adelante que solucione estos inconvenientes se puede reabrir y linkearlo con el trabajo realizado.

**Comment by maximocanedo** [comment]
Cierro esta Issue porque, después de investigar un poco llegué a la conclusión de que es muy complicado realizar esto.
Se necesita manipular el evento mediante Javascript y luego hacer un PostBack.
![image](https://github.com/maximocanedo/PROGIII-TPI/assets/103539894/135b4899-67e5-4e1a-9c17-bcf96c0d33fd)
![image](https://github.com/maximocanedo/PROGIII-TPI/assets/103539894/a20d426d-cd6f-441b-b659-97747f9574a7)
![image](https://github.com/maximocanedo/PROGIII-TPI/assets/103539894/6d77f698-7281-494a-9ce4-17b4c58697ba)

El problema con esto es que necesita hacer PostBack para que C# lo pueda manejar. 
Y con PostBack, imposibilita el ingreso de la contraseña, dado que cuando se hace click en el `txtClave`, se realiza PostBack, y si se desactiva el PostBack no funciona nada.

Doy por cerrado esta Issue. Aunque si se encuentra una solución más adelante que solucione estos inconvenientes se puede reabrir y linkearlo con el trabajo realizado.
