### ISSUE TITLE
¿Las ventas se pueden eliminar?

### ISSUE THREAD

**Issue by maximocanedo** [maximocanedo/PROGIII-TPI#50]
Queda poco tiempo para entregar, y me di cuenta de que Ventas no tiene en sí funciones de Datos o Negocio, ni siquiera en Vistas, que faciliten deshabilitar un registro de tipo Venta.

Opciones:

- Usar `DELETE FROM Ventas` y `DELETE FROM DetalleDeVenta WHERE CodVenta = VentaID` Para eliminar ventas junto con sus detalles.
- No hacer nada.

Qué opinan/eligen? Se aceptan propuestas.
@JtoralesK @maximocanedo @Jean5011 @Mizzar229 @Oli-Hanczyc

**Comment by Mizzar229** [comment]
No se hasta que punto seria útil eliminar los registros de ventas enteros ya que suelen ser registros muy importantes en las tiendas. 
El registro de venta sirve para que las empresas mantengan el control de las ventas, y adquieran datos útiles que les permitan tomar decisiones de venta más inteligentes. Propongo que no hagamos nada y lo dejemos sin la opción de eliminar

**Comment by Oli-Hanczyc** [comment]
Yo veo conveniente eliminar una venta solamente si no se vende más un producto determinado (es decir, eliminar la venta relacionada a ese producto). Pero igualmente también estoy de acuerdo con lo que dijo Ezequiel, además de que creo que nos complicaríamos en vano.
Saludos!

**Comment by maximocanedo** [comment]
Al final había decidido que lo mejor era permitir la baja física. Es cierto que pueden ser registros muy importantes pero también se dan casos en los que la venta se cancela o se reembolsa.
Dicha funcionalidad ya está implementada.
