### ISSUE TITLE
FILTRAR AL BUSCAR

### ISSUE THREAD

**Issue by maximocanedo** [maximocanedo/PROGIII-TPI#54]
Una pauta que no cumplimos fue la de implementar filtros a la hora de buscar.
Filtros como un checkbox de "Sólo registros habilitados", un DDL de "Categoría a buscar", "Proveedor a buscar" entre los productos, por ejemplo.
Es de suma importancia terminarlo antes del lunes.
Yo me encargo de Empleados y Sesiones.

**Comment by maximocanedo** [comment]
Yo me encargo de Empleados y Sesiones:

- [ ] Empleados
      - [ ] Filtrar por sexo (DDL)
      - [ ] Filtrar por rol (DDL, opcional CheckBox)
      - [ ] Filtrar por estado (DDL, opcional CheckBox)
- [ ] Sesiones
      - [ ] Filtrar por estado (Revocado, Autorizado) (DDL, opcional CheckBox)

**Comment by maximocanedo** [comment]
Empleados

- [ ] Filtrar por sexo (DDL)
- [ ] Filtrar por rol (DDL, opcional CheckBox)
- [ ] Filtrar por estado (DDL, opcional CheckBox)

**Comment by maximocanedo** [comment]
Sesiones

- [ ] Filtrar por estado (Revocado/Autorizado) (DDL, opcional CheckBox)

**Comment by maximocanedo** [comment]
IDEA PARA FILTRAR PRODUCTOS:
Un DDL para filtrar por cantidad de Stock:
Opciones del DDL:

- Sin Stock: Productos con 0 stock
- Bajo Stock: Productos con stock menor o igual a 5
- Alto Stock: Productos con stock mayor a 5
- Todos: No filtrar por stock.

@Mizzar229 @JtoralesK no sé quién de ustedes se va a encargar de FILTRAR PRODUCTOS.

**Comment by maximocanedo** [comment]
La idea anterior es una. 
Productos puede filtrarse por Proveedor, Categoría, Estado, etc.

**Comment by Mizzar229** [comment]
Me encargo de filtrar Productos

**Comment by Mizzar229** [comment]
Filtrar Producto completado por mi compañero Javier Torales
También se añadió una opción de Filtrar por Activos en Tipo de Producto

- [ ] Filtrar por Stock Producto
- [ ] Filtrar por Estado Tipo de Producto
