### ISSUE TITLE
Agregar funcionalidad a las páginas de Proveedores

### ISSUE THREAD

**Issue by maximocanedo** [maximocanedo/PROGIII-TPI#6]
Las páginas de Vistas/Proveedores no están bien hechas.
Sólo tienen código HTML, y en el caso de una, tiene un código comentado que no iba ahí, y que no respeta la estructura Datos/Negocio/Vistas.
Se pide a quien pueda que provea de funcionalidad a las páginas.

**Comment by JtoralesK** [comment]
Realize las funcionalidades para actualizar proveedor, eliminar(lógico) proveedor, filtrar por cuit de proveedor y agregar proveedor.
